#!/bin/bash

# Colors
RED_ECHO='\033[0;31m'
GREEN_ECHO='\e[32m'
WHITE_ECHO='\033[0m'
ROOT_DIR="$(pwd)/"

LIST=$(git diff --cached --name-status | grep -E '^(M|A)' | grep php$)
ERRORS_BUFFER=""
for file in $LIST
do
    if [ $(echo "$file" | grep '^M$') ]; then
        FILE_ACTION="modified"
    elif [ $(echo "$file" | grep '^A$') ]; then
        FILE_ACTION="added"
    else
        if [ "$file" != "" ]; then
            ERRORS=$(php -l $ROOT_DIR$file 2>&1 | grep "Parse error")
            if [ "$ERRORS" != "" ]; then
                if [ "$ERRORS_BUFFER" != "" ]; then
                    ERRORS_BUFFER="$ERRORS_BUFFER\n$ERRORS"
                else
                    ERRORS_BUFFER="$ERRORS"
                fi
                echo -e $RED_ECHO"Syntax errors found in file: $file"$WHITE_ECHO
	    else
	        echo -e $GREEN_ECHO"Checked $FILE_ACTION file: $file"$WHITE_ECHO
	    fi
        fi
    fi
done
if [ "$ERRORS_BUFFER" != "" ]; then
    echo 
    echo "These errors were found in try-to-commit files: "
    echo -e $ERRORS_BUFFER
    echo 
    echo -e $RED_ECHO"Can't commit, fix errors first."$WHITE_ECHO
    exit 1
else
    echo -e $GREEN_ECHO"Commited successfully."$WHITE_ECHO
fi
